echo "#!/bin/bash"
echo "############################################################################################################"
echo "#	___This Is A___                                                                                    #"
echo "# By; Shazza-Works. Program Licence Free Do What You Want.                                                 #"
echo "# Email; ogormanad@googlemail.com                                                                          #"
echo "############################################################################################################"
echo "#"
echo "#"
